FROM ruby:3.3.0-slim

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  curl \
  ca-certificates \
  autoconf \
  automake \
  libtool \
  pkg-config \
  libsecp256k1-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./
ENV BUNDLE_BUILD__RBSECP256K1=--with-system-libraries
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
