source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

gem 'rails', '~> 7.2.2.1'
gem 'puma', '~> 6.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :test do
  gem 'factory_bot_rails'
end

#####

gem 'mongoid'

gem 'dotenv'
gem 'rack-cors'

gem 'bcrypt', '~> 3.1.7'
gem 'jwt'

gem 'active_model_serializers'

gem 'resend'

gem 'sidekiq'

gem 'rrule'

gem 'stripe'

gem 'lograge'

gem 'aws-sdk-lambda'

gem 'siwe'

gem 'google-id-token'

gem 'dry-validation'

gem 'trailblazer'

group :development, :test do
  gem 'rspec-rails'
  gem 'rswag-api'
  gem 'rswag-specs'
end