/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateImport } from './routes/_private'
import { Route as PrivateSidebarImport } from './routes/_private/_sidebar'
import { Route as publicAuthImport } from './routes/(public)/_auth'
import { Route as PrivateFreezedIndexImport } from './routes/_private/freezed/index'
import { Route as PrivateCheckoutIndexImport } from './routes/_private/checkout/index'
import { Route as PrivateSidebarDashboardIndexImport } from './routes/_private/_sidebar/dashboard/index'
import { Route as PrivateSidebarAnalyticsIndexImport } from './routes/_private/_sidebar/analytics/index'
import { Route as PrivateSidebarAccountLayoutImport } from './routes/_private/_sidebar/account/_layout'
import { Route as PrivateSidebarAccountLayoutSubscriptionIndexImport } from './routes/_private/_sidebar/account/_layout/subscription/index'
import { Route as PrivateSidebarAccountLayoutPlansIndexImport } from './routes/_private/_sidebar/account/_layout/plans/index'
import { Route as PrivateSidebarAccountLayoutGeneralIndexImport } from './routes/_private/_sidebar/account/_layout/general/index'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()
const IndexLazyImport = createFileRoute('/')()
const PrivateSidebarAccountImport = createFileRoute(
  '/_private/_sidebar/account',
)()
const publicAuthSignUpIndexLazyImport = createFileRoute(
  '/(public)/_auth/sign-up/',
)()
const publicAuthSignInIndexLazyImport = createFileRoute(
  '/(public)/_auth/sign-in/',
)()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PrivateSidebarRoute = PrivateSidebarImport.update({
  id: '/_sidebar',
  getParentRoute: () => PrivateRoute,
} as any)

const publicAuthRoute = publicAuthImport.update({
  id: '/_auth',
  getParentRoute: () => publicRoute,
} as any)

const PrivateSidebarAccountRoute = PrivateSidebarAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PrivateSidebarRoute,
} as any)

const PrivateFreezedIndexRoute = PrivateFreezedIndexImport.update({
  id: '/freezed/',
  path: '/freezed/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateCheckoutIndexRoute = PrivateCheckoutIndexImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => PrivateRoute,
} as any)

const publicAuthSignUpIndexLazyRoute = publicAuthSignUpIndexLazyImport
  .update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => publicAuthRoute,
  } as any)
  .lazy(() =>
    import('./routes/(public)/_auth/sign-up/index.lazy').then((d) => d.Route),
  )

const publicAuthSignInIndexLazyRoute = publicAuthSignInIndexLazyImport
  .update({
    id: '/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => publicAuthRoute,
  } as any)
  .lazy(() =>
    import('./routes/(public)/_auth/sign-in/index.lazy').then((d) => d.Route),
  )

const PrivateSidebarDashboardIndexRoute =
  PrivateSidebarDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => PrivateSidebarRoute,
  } as any)

const PrivateSidebarAnalyticsIndexRoute =
  PrivateSidebarAnalyticsIndexImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => PrivateSidebarRoute,
  } as any)

const PrivateSidebarAccountLayoutRoute =
  PrivateSidebarAccountLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => PrivateSidebarAccountRoute,
  } as any)

const PrivateSidebarAccountLayoutSubscriptionIndexRoute =
  PrivateSidebarAccountLayoutSubscriptionIndexImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => PrivateSidebarAccountLayoutRoute,
  } as any)

const PrivateSidebarAccountLayoutPlansIndexRoute =
  PrivateSidebarAccountLayoutPlansIndexImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => PrivateSidebarAccountLayoutRoute,
  } as any)

const PrivateSidebarAccountLayoutGeneralIndexRoute =
  PrivateSidebarAccountLayoutGeneralIndexImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => PrivateSidebarAccountLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_auth': {
      id: '/(public)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicAuthImport
      parentRoute: typeof publicRoute
    }
    '/_private/_sidebar': {
      id: '/_private/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateSidebarImport
      parentRoute: typeof PrivateImport
    }
    '/_private/checkout/': {
      id: '/_private/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PrivateCheckoutIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/freezed/': {
      id: '/_private/freezed/'
      path: '/freezed'
      fullPath: '/freezed'
      preLoaderRoute: typeof PrivateFreezedIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/_sidebar/account': {
      id: '/_private/_sidebar/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PrivateSidebarAccountImport
      parentRoute: typeof PrivateSidebarImport
    }
    '/_private/_sidebar/account/_layout': {
      id: '/_private/_sidebar/account/_layout'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PrivateSidebarAccountLayoutImport
      parentRoute: typeof PrivateSidebarAccountRoute
    }
    '/_private/_sidebar/analytics/': {
      id: '/_private/_sidebar/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof PrivateSidebarAnalyticsIndexImport
      parentRoute: typeof PrivateSidebarImport
    }
    '/_private/_sidebar/dashboard/': {
      id: '/_private/_sidebar/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateSidebarDashboardIndexImport
      parentRoute: typeof PrivateSidebarImport
    }
    '/(public)/_auth/sign-in/': {
      id: '/(public)/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicAuthSignInIndexLazyImport
      parentRoute: typeof publicAuthImport
    }
    '/(public)/_auth/sign-up/': {
      id: '/(public)/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicAuthSignUpIndexLazyImport
      parentRoute: typeof publicAuthImport
    }
    '/_private/_sidebar/account/_layout/general/': {
      id: '/_private/_sidebar/account/_layout/general/'
      path: '/general'
      fullPath: '/account/general'
      preLoaderRoute: typeof PrivateSidebarAccountLayoutGeneralIndexImport
      parentRoute: typeof PrivateSidebarAccountLayoutImport
    }
    '/_private/_sidebar/account/_layout/plans/': {
      id: '/_private/_sidebar/account/_layout/plans/'
      path: '/plans'
      fullPath: '/account/plans'
      preLoaderRoute: typeof PrivateSidebarAccountLayoutPlansIndexImport
      parentRoute: typeof PrivateSidebarAccountLayoutImport
    }
    '/_private/_sidebar/account/_layout/subscription/': {
      id: '/_private/_sidebar/account/_layout/subscription/'
      path: '/subscription'
      fullPath: '/account/subscription'
      preLoaderRoute: typeof PrivateSidebarAccountLayoutSubscriptionIndexImport
      parentRoute: typeof PrivateSidebarAccountLayoutImport
    }
  }
}

// Create and export the route tree

interface PrivateSidebarAccountLayoutRouteChildren {
  PrivateSidebarAccountLayoutGeneralIndexRoute: typeof PrivateSidebarAccountLayoutGeneralIndexRoute
  PrivateSidebarAccountLayoutPlansIndexRoute: typeof PrivateSidebarAccountLayoutPlansIndexRoute
  PrivateSidebarAccountLayoutSubscriptionIndexRoute: typeof PrivateSidebarAccountLayoutSubscriptionIndexRoute
}

const PrivateSidebarAccountLayoutRouteChildren: PrivateSidebarAccountLayoutRouteChildren =
  {
    PrivateSidebarAccountLayoutGeneralIndexRoute:
      PrivateSidebarAccountLayoutGeneralIndexRoute,
    PrivateSidebarAccountLayoutPlansIndexRoute:
      PrivateSidebarAccountLayoutPlansIndexRoute,
    PrivateSidebarAccountLayoutSubscriptionIndexRoute:
      PrivateSidebarAccountLayoutSubscriptionIndexRoute,
  }

const PrivateSidebarAccountLayoutRouteWithChildren =
  PrivateSidebarAccountLayoutRoute._addFileChildren(
    PrivateSidebarAccountLayoutRouteChildren,
  )

interface PrivateSidebarAccountRouteChildren {
  PrivateSidebarAccountLayoutRoute: typeof PrivateSidebarAccountLayoutRouteWithChildren
}

const PrivateSidebarAccountRouteChildren: PrivateSidebarAccountRouteChildren = {
  PrivateSidebarAccountLayoutRoute:
    PrivateSidebarAccountLayoutRouteWithChildren,
}

const PrivateSidebarAccountRouteWithChildren =
  PrivateSidebarAccountRoute._addFileChildren(
    PrivateSidebarAccountRouteChildren,
  )

interface PrivateSidebarRouteChildren {
  PrivateSidebarAccountRoute: typeof PrivateSidebarAccountRouteWithChildren
  PrivateSidebarAnalyticsIndexRoute: typeof PrivateSidebarAnalyticsIndexRoute
  PrivateSidebarDashboardIndexRoute: typeof PrivateSidebarDashboardIndexRoute
}

const PrivateSidebarRouteChildren: PrivateSidebarRouteChildren = {
  PrivateSidebarAccountRoute: PrivateSidebarAccountRouteWithChildren,
  PrivateSidebarAnalyticsIndexRoute: PrivateSidebarAnalyticsIndexRoute,
  PrivateSidebarDashboardIndexRoute: PrivateSidebarDashboardIndexRoute,
}

const PrivateSidebarRouteWithChildren = PrivateSidebarRoute._addFileChildren(
  PrivateSidebarRouteChildren,
)

interface PrivateRouteChildren {
  PrivateSidebarRoute: typeof PrivateSidebarRouteWithChildren
  PrivateCheckoutIndexRoute: typeof PrivateCheckoutIndexRoute
  PrivateFreezedIndexRoute: typeof PrivateFreezedIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateSidebarRoute: PrivateSidebarRouteWithChildren,
  PrivateCheckoutIndexRoute: PrivateCheckoutIndexRoute,
  PrivateFreezedIndexRoute: PrivateFreezedIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface publicAuthRouteChildren {
  publicAuthSignInIndexLazyRoute: typeof publicAuthSignInIndexLazyRoute
  publicAuthSignUpIndexLazyRoute: typeof publicAuthSignUpIndexLazyRoute
}

const publicAuthRouteChildren: publicAuthRouteChildren = {
  publicAuthSignInIndexLazyRoute: publicAuthSignInIndexLazyRoute,
  publicAuthSignUpIndexLazyRoute: publicAuthSignUpIndexLazyRoute,
}

const publicAuthRouteWithChildren = publicAuthRoute._addFileChildren(
  publicAuthRouteChildren,
)

interface publicRouteChildren {
  publicAuthRoute: typeof publicAuthRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicAuthRoute: publicAuthRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof publicAuthRouteWithChildren
  '': typeof PrivateSidebarRouteWithChildren
  '/checkout': typeof PrivateCheckoutIndexRoute
  '/freezed': typeof PrivateFreezedIndexRoute
  '/account': typeof PrivateSidebarAccountLayoutRouteWithChildren
  '/analytics': typeof PrivateSidebarAnalyticsIndexRoute
  '/dashboard': typeof PrivateSidebarDashboardIndexRoute
  '/sign-in': typeof publicAuthSignInIndexLazyRoute
  '/sign-up': typeof publicAuthSignUpIndexLazyRoute
  '/account/general': typeof PrivateSidebarAccountLayoutGeneralIndexRoute
  '/account/plans': typeof PrivateSidebarAccountLayoutPlansIndexRoute
  '/account/subscription': typeof PrivateSidebarAccountLayoutSubscriptionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof publicAuthRouteWithChildren
  '': typeof PrivateSidebarRouteWithChildren
  '/checkout': typeof PrivateCheckoutIndexRoute
  '/freezed': typeof PrivateFreezedIndexRoute
  '/account': typeof PrivateSidebarAccountLayoutRouteWithChildren
  '/analytics': typeof PrivateSidebarAnalyticsIndexRoute
  '/dashboard': typeof PrivateSidebarDashboardIndexRoute
  '/sign-in': typeof publicAuthSignInIndexLazyRoute
  '/sign-up': typeof publicAuthSignUpIndexLazyRoute
  '/account/general': typeof PrivateSidebarAccountLayoutGeneralIndexRoute
  '/account/plans': typeof PrivateSidebarAccountLayoutPlansIndexRoute
  '/account/subscription': typeof PrivateSidebarAccountLayoutSubscriptionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_private': typeof PrivateRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_auth': typeof publicAuthRouteWithChildren
  '/_private/_sidebar': typeof PrivateSidebarRouteWithChildren
  '/_private/checkout/': typeof PrivateCheckoutIndexRoute
  '/_private/freezed/': typeof PrivateFreezedIndexRoute
  '/_private/_sidebar/account': typeof PrivateSidebarAccountRouteWithChildren
  '/_private/_sidebar/account/_layout': typeof PrivateSidebarAccountLayoutRouteWithChildren
  '/_private/_sidebar/analytics/': typeof PrivateSidebarAnalyticsIndexRoute
  '/_private/_sidebar/dashboard/': typeof PrivateSidebarDashboardIndexRoute
  '/(public)/_auth/sign-in/': typeof publicAuthSignInIndexLazyRoute
  '/(public)/_auth/sign-up/': typeof publicAuthSignUpIndexLazyRoute
  '/_private/_sidebar/account/_layout/general/': typeof PrivateSidebarAccountLayoutGeneralIndexRoute
  '/_private/_sidebar/account/_layout/plans/': typeof PrivateSidebarAccountLayoutPlansIndexRoute
  '/_private/_sidebar/account/_layout/subscription/': typeof PrivateSidebarAccountLayoutSubscriptionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/checkout'
    | '/freezed'
    | '/account'
    | '/analytics'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/account/general'
    | '/account/plans'
    | '/account/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/checkout'
    | '/freezed'
    | '/account'
    | '/analytics'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/account/general'
    | '/account/plans'
    | '/account/subscription'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/(public)'
    | '/(public)/_auth'
    | '/_private/_sidebar'
    | '/_private/checkout/'
    | '/_private/freezed/'
    | '/_private/_sidebar/account'
    | '/_private/_sidebar/account/_layout'
    | '/_private/_sidebar/analytics/'
    | '/_private/_sidebar/dashboard/'
    | '/(public)/_auth/sign-in/'
    | '/(public)/_auth/sign-up/'
    | '/_private/_sidebar/account/_layout/general/'
    | '/_private/_sidebar/account/_layout/plans/'
    | '/_private/_sidebar/account/_layout/subscription/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PrivateRoute: PrivateRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_private",
        "/(public)"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/_sidebar",
        "/_private/checkout/",
        "/_private/freezed/"
      ]
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/_auth"
      ]
    },
    "/(public)/_auth": {
      "filePath": "(public)/_auth.tsx",
      "parent": "/(public)",
      "children": [
        "/(public)/_auth/sign-in/",
        "/(public)/_auth/sign-up/"
      ]
    },
    "/_private/_sidebar": {
      "filePath": "_private/_sidebar.tsx",
      "parent": "/_private",
      "children": [
        "/_private/_sidebar/account",
        "/_private/_sidebar/analytics/",
        "/_private/_sidebar/dashboard/"
      ]
    },
    "/_private/checkout/": {
      "filePath": "_private/checkout/index.tsx",
      "parent": "/_private"
    },
    "/_private/freezed/": {
      "filePath": "_private/freezed/index.tsx",
      "parent": "/_private"
    },
    "/_private/_sidebar/account": {
      "filePath": "_private/_sidebar/account",
      "parent": "/_private/_sidebar",
      "children": [
        "/_private/_sidebar/account/_layout"
      ]
    },
    "/_private/_sidebar/account/_layout": {
      "filePath": "_private/_sidebar/account/_layout.tsx",
      "parent": "/_private/_sidebar/account",
      "children": [
        "/_private/_sidebar/account/_layout/general/",
        "/_private/_sidebar/account/_layout/plans/",
        "/_private/_sidebar/account/_layout/subscription/"
      ]
    },
    "/_private/_sidebar/analytics/": {
      "filePath": "_private/_sidebar/analytics/index.tsx",
      "parent": "/_private/_sidebar"
    },
    "/_private/_sidebar/dashboard/": {
      "filePath": "_private/_sidebar/dashboard/index.tsx",
      "parent": "/_private/_sidebar"
    },
    "/(public)/_auth/sign-in/": {
      "filePath": "(public)/_auth/sign-in/index.lazy.tsx",
      "parent": "/(public)/_auth"
    },
    "/(public)/_auth/sign-up/": {
      "filePath": "(public)/_auth/sign-up/index.lazy.tsx",
      "parent": "/(public)/_auth"
    },
    "/_private/_sidebar/account/_layout/general/": {
      "filePath": "_private/_sidebar/account/_layout/general/index.tsx",
      "parent": "/_private/_sidebar/account/_layout"
    },
    "/_private/_sidebar/account/_layout/plans/": {
      "filePath": "_private/_sidebar/account/_layout/plans/index.tsx",
      "parent": "/_private/_sidebar/account/_layout"
    },
    "/_private/_sidebar/account/_layout/subscription/": {
      "filePath": "_private/_sidebar/account/_layout/subscription/index.tsx",
      "parent": "/_private/_sidebar/account/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
