/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicSignUpIndexImport } from './routes/(public)/sign-up/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const publicSignInIndexLazyImport = createFileRoute('/(public)/sign-in/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const publicSignInIndexLazyRoute = publicSignInIndexLazyImport
  .update({
    id: '/(public)/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(public)/sign-in/index.lazy').then((d) => d.Route),
  )

const publicSignUpIndexRoute = publicSignUpIndexImport.update({
  id: '/(public)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(public)/sign-up/': {
      id: '/(public)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpIndexImport
      parentRoute: typeof rootRoute
    }
    '/(public)/sign-in/': {
      id: '/(public)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/sign-up': typeof publicSignUpIndexRoute
  '/sign-in': typeof publicSignInIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/sign-up': typeof publicSignUpIndexRoute
  '/sign-in': typeof publicSignInIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/(public)/sign-up/': typeof publicSignUpIndexRoute
  '/(public)/sign-in/': typeof publicSignInIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-up' | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-up' | '/sign-in'
  id: '__root__' | '/' | '/(public)/sign-up/' | '/(public)/sign-in/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  publicSignUpIndexRoute: typeof publicSignUpIndexRoute
  publicSignInIndexLazyRoute: typeof publicSignInIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  publicSignUpIndexRoute: publicSignUpIndexRoute,
  publicSignInIndexLazyRoute: publicSignInIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(public)/sign-up/",
        "/(public)/sign-in/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/(public)/sign-up/": {
      "filePath": "(public)/sign-up/index.tsx"
    },
    "/(public)/sign-in/": {
      "filePath": "(public)/sign-in/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
