/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateImport } from './routes/_private'
import { Route as publicAuthImport } from './routes/(public)/_auth'
import { Route as PrivateDashboardIndexImport } from './routes/_private/dashboard/index'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()
const IndexLazyImport = createFileRoute('/')()
const publicAuthSignUpIndexLazyImport = createFileRoute(
  '/(public)/_auth/sign-up/',
)()
const publicAuthSignInIndexLazyImport = createFileRoute(
  '/(public)/_auth/sign-in/',
)()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const publicAuthRoute = publicAuthImport.update({
  id: '/_auth',
  getParentRoute: () => publicRoute,
} as any)

const PrivateDashboardIndexRoute = PrivateDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PrivateRoute,
} as any)

const publicAuthSignUpIndexLazyRoute = publicAuthSignUpIndexLazyImport
  .update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => publicAuthRoute,
  } as any)
  .lazy(() =>
    import('./routes/(public)/_auth/sign-up/index.lazy').then((d) => d.Route),
  )

const publicAuthSignInIndexLazyRoute = publicAuthSignInIndexLazyImport
  .update({
    id: '/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => publicAuthRoute,
  } as any)
  .lazy(() =>
    import('./routes/(public)/_auth/sign-in/index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_auth': {
      id: '/(public)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicAuthImport
      parentRoute: typeof publicRoute
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardIndexImport
      parentRoute: typeof PrivateImport
    }
    '/(public)/_auth/sign-in/': {
      id: '/(public)/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicAuthSignInIndexLazyImport
      parentRoute: typeof publicAuthImport
    }
    '/(public)/_auth/sign-up/': {
      id: '/(public)/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicAuthSignUpIndexLazyImport
      parentRoute: typeof publicAuthImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteChildren {
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface publicAuthRouteChildren {
  publicAuthSignInIndexLazyRoute: typeof publicAuthSignInIndexLazyRoute
  publicAuthSignUpIndexLazyRoute: typeof publicAuthSignUpIndexLazyRoute
}

const publicAuthRouteChildren: publicAuthRouteChildren = {
  publicAuthSignInIndexLazyRoute: publicAuthSignInIndexLazyRoute,
  publicAuthSignUpIndexLazyRoute: publicAuthSignUpIndexLazyRoute,
}

const publicAuthRouteWithChildren = publicAuthRoute._addFileChildren(
  publicAuthRouteChildren,
)

interface publicRouteChildren {
  publicAuthRoute: typeof publicAuthRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicAuthRoute: publicAuthRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof publicAuthRouteWithChildren
  '': typeof PrivateRouteWithChildren
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/sign-in': typeof publicAuthSignInIndexLazyRoute
  '/sign-up': typeof publicAuthSignUpIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof publicAuthRouteWithChildren
  '': typeof PrivateRouteWithChildren
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/sign-in': typeof publicAuthSignInIndexLazyRoute
  '/sign-up': typeof publicAuthSignUpIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_private': typeof PrivateRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_auth': typeof publicAuthRouteWithChildren
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
  '/(public)/_auth/sign-in/': typeof publicAuthSignInIndexLazyRoute
  '/(public)/_auth/sign-up/': typeof publicAuthSignUpIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/dashboard' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/dashboard' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/(public)'
    | '/(public)/_auth'
    | '/_private/dashboard/'
    | '/(public)/_auth/sign-in/'
    | '/(public)/_auth/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PrivateRoute: PrivateRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_private",
        "/(public)"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/dashboard/"
      ]
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/_auth"
      ]
    },
    "/(public)/_auth": {
      "filePath": "(public)/_auth.tsx",
      "parent": "/(public)",
      "children": [
        "/(public)/_auth/sign-in/",
        "/(public)/_auth/sign-up/"
      ]
    },
    "/_private/dashboard/": {
      "filePath": "_private/dashboard/index.tsx",
      "parent": "/_private"
    },
    "/(public)/_auth/sign-in/": {
      "filePath": "(public)/_auth/sign-in/index.lazy.tsx",
      "parent": "/(public)/_auth"
    },
    "/(public)/_auth/sign-up/": {
      "filePath": "(public)/_auth/sign-up/index.lazy.tsx",
      "parent": "/(public)/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
